Update spec helps to newer version
puppetlabs/support-tasks pull request #138
Opened 2022-04-06 17:25 UTC by m0dular

2022-04-13 08:09 UTC, MartyEwings requested changes
We need .github/workflows/pr_test.yml for this to have proper coverage

2022-05-16 10:21 UTC, elainemccloskey approved these changes

2022-05-16 10:22 UTC, elainemccloskey approved these changes

2022-05-16 10:22 UTC, MartyEwings approved these changes

2022-05-16 10:22 UTC, merged