W.I.P - Sup 4423 deprecation of cert tool
puppetlabs/support-tasks pull request #166
Opened 2023-10-27 13:15 UTC by Aaronoftheages

2023-10-30 18:54 UTC, m0dular requested changes
I did some testing and think we should add the deprecation as a key to the results output.  I made a branch with the changes, specifically [here](https://github.com/m0dular/support-tasks/blob/13d02d3f3e9f0a557f9944d10c0edc17aeefe742/tasks/st0317a_clean_cert.rb#L48-L51) to add the message to the results and [here](https://github.com/m0dular/support-tasks/blob/13d02d3f3e9f0a557f9944d10c0edc17aeefe742/tasks/st0317a_clean_cert.rb#L68) to avoid failing because of the message.

With that you get a message in the output that looks like 

```
{
    "deprecation": "This task is deprecated and has been replaced by the certificate clean api, which provides the same functionality. This task will be removed in a future release.  Please see this module's README for more information"
}

2023-10-30 18:54 UTC, m0dular commented on tasks/st0317a_clean_cert.rb
> +  puts '***THIS TASK IS NOW DEPRECATED - Please see README*** - This task can only be run on your certificate authority Puppetserver'
I don't really like adding this message to everything the script may output.  We should add it to the README and the main results, but I think we should remove this one.

2023-10-30 18:54 UTC, m0dular commented on tasks/st0317a_clean_cert.json
> +  "description": "***DEPRECATION NOTICE - This task is unsupported and will be removed in a future version*** - Clean (remove) a Puppet agent's certificate from your Primary Server",
I don't think adding the deprecation here is necessary.

2023-10-30 18:54 UTC, m0dular commented on tasks/st0317a_clean_cert.rb
> +    results[agent][:result] = '***THIS TASK IS NOW DEPRECATED - Please see README*** - Refusing to remove the Puppet Primary Server certificate'
Same as the others, we shouldn't add the deprecation to the results of each certname we try to clean.  Please remove it from here.

2023-10-30 18:54 UTC, m0dular commented on tasks/st0317a_clean_cert.rb
> +exit(results.values.all? { |v| v[:result] == '***THIS TASK IS NOW DEPRECATED - Please see README*** - Certificate removed' }) ? 0 : 1
Same as the others, we shouldn't add the deprecation to the results of each certname we try to clean. Please remove it from here.

2023-10-31 16:39 UTC, m0dular requested changes
Just one Rubocop warning left, but I'm still concerned about why this is running the old Github Actions workflows.  @Aaronoftheages Could you close this PR, make the linting change, and open a new one without squashing or rebasing?  It's fine to have one additional commit that says "Linting fixes" or something.

2023-10-31 16:39 UTC, m0dular commented on tasks/st0317a_clean_cert.rb
> +deprecation_msg = "This task is deprecated and has been replaced by the certificate clean api, which provides the same functionality.
There's still a warning about whitespace on this line.  A `pdk validate -a` should fix it.

2023-10-31 16:44 UTC, Aaronoftheages commented
Rubocop Issues, closing and restarting

2023-10-31 16:44 UTC, closed without merging