Sup-4597 - Deprecation of support_script_and_upload task [st0305]
puppetlabs/support-tasks pull request #175
Opened 2023-11-03 16:11 UTC by Aaronoftheages

The deprecation of task 305 with deprecation message added during runtime - an example of the output is below:

`{
  "result" : "Creating output directory: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021\n\nEvaluating check: base-status\n\n ** Adding data to: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/metadata.json\n\nEvaluating scope: system\n\nEvaluating check: system.config\n\n ** Collecting output of: sestatus >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/selinux.txt' 2>&1\n\n ** Collecting output of: sysctl -a >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/sysctl.txt' 2>&1\n\n ** Collecting output of: umask >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/umask.txt' 2>&1\n\n ** Collecting output of: uname -a >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/uname.txt' 2>&1\n\n ** Copying: /etc/hosts\n\n ** Copying: /etc/nsswitch.conf\n\n ** Copying: /etc/os-release\n\n ** Copying: /etc/resolv.conf\n\n ** Copying: /etc/yum.conf\n\n ** Copying: /etc/yum.repos.d\n\n ** Adding data to: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/hostname_output.txt\n\n ** Collecting output of: ifconfig -a >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/ifconfig.txt' 2>&1\n\n ** Collecting output of: iptables -L -n >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/ip_tables.txt' 2>&1\n\n ** Collecting output of: ip6tables -L -n >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/ip_tables.txt' 2>&1\n\nEvaluating check: system.logs\n\n ** Compressing: /var/log/messages\n\n ** Collecting output of: dmesg --ctime >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/logs/dmesg.txt' 2>&1\n\nEvaluating check: system.status\n\n ** Collecting output of: env >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/env.txt' 2>&1\n\n ** Collecting output of: ps -aux >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/ps_aux.txt' 2>&1\n\n ** Collecting output of: ps -e f >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/ps_tree.txt' 2>&1\n\n ** Collecting output of: chkconfig --list >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/services.txt' 2>&1\n\n ** Collecting output of: systemctl list-units >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/services.txt' 2>&1\n\n ** Collecting output of: systemctl list-timers >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/timers.txt' 2>&1\n\n ** Collecting output of: uptime >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/uptime.txt' 2>&1\n\n ** Collecting output of: netstat -anptuo >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/ports.txt' 2>&1\n\n ** Collecting output of: nstat -a >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/nstat_output.txt' 2>&1\n\n ** Adding data to: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/guessed_ip_address.txt\n\n ** Collecting output of: getent hosts '10.253.3.176\n\n' >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/mapped_hostname_from_guessed_ip_address.txt' 2>&1\n\n ** Collecting output of: df -h >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/resources/df_output.txt' 2>&1\n\n ** Collecting output of: df -i >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/resources/df_output.txt' 2>&1\n\n ** Collecting output of: df -k >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/resources/df_inodes_output.txt' 2>&1\n\n ** Collecting output of: free -h >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/resources/free_mem.txt' 2>&1\n\nEvaluating check: system.metrics\n\nEvaluating scope: puppet-agent\n\nEvaluating check: puppet-agent.config\n\n ** Copying: /etc/puppetlabs/puppet/hiera.yaml\n\n ** Copying: /etc/puppetlabs/puppet/puppet.conf\n\n ** Copying: /etc/puppetlabs/pxp-agent/modules\n\n ** Copying: /etc/puppetlabs/pxp-agent/pxp-agent.conf\n\n ** Copying: /etc/sysconfig/puppet\n\n ** Copying: /etc/sysconfig/pxp-agent\n\nEvaluating check: puppet-agent.logs\n\n ** Copying: /var/log/puppetlabs/puppet\n\n ** Copying: /var/log/puppetlabs/pxp-agent\n\n ** Collecting output of: journalctl --full --output=short-iso --unit puppet  --since '3 days ago' >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/logs/puppet/puppet-journalctl.log' 2>&1\n\n ** Collecting output of: journalctl --full --output=short-iso --unit pxp-agent  --since '3 days ago' >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/logs/pxp-agent/pxp-agent-journalctl.log' 2>&1\n\nEvaluating check: puppet-agent.status\n\n ** Collecting output of: systemctl status 'puppet.service' >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/systemctl-status.txt' 2>&1\n\n ** Collecting output of: systemctl status 'pxp-agent.service' >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/systemctl-status.txt' 2>&1\n\n ** Copying: /proc/858/cmdline\n\n ** Copying: /proc/858/limits\n\n ** Copying: /proc/858/environ\n\n ** Copying: /proc/858/smaps\n\n ** Adding data to: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/proc/puppet/exe\n\n ** Copying: /sys/fs/cgroup/devices/system.slice/puppet.service/\n\n ** Copying: /sys/fs/cgroup/systemd/system.slice/puppet.service/\n\n ** Copying: /proc/853/cmdline\n\n ** Copying: /proc/853/limits\n\n ** Copying: /proc/853/environ\n\n ** Copying: /proc/853/smaps\n\n ** Copying: /proc/5677/cmdline\n\n ** Copying: /proc/5677/limits\n\n ** Copying: /proc/5677/environ\n\n ** Copying: /proc/5677/smaps\n\n ** Copying: /proc/5678/cmdline\n\n ** Copying: /proc/5678/limits\n\n ** Copying: /proc/5678/environ\n\n ** Copying: /proc/5678/smaps\n\n ** Copying: /proc/5680/cmdline\n\n ** Copying: /proc/5680/limits\n\n ** Copying: /proc/5680/environ\n\n ** Copying: /proc/5680/smaps\n\n ** Adding data to: /var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/proc/pxp-agent/exe\n\n ** Copying: /sys/fs/cgroup/devices/system.slice/pxp-agent.service/\n\n ** Copying: /sys/fs/cgroup/systemd/system.slice/pxp-agent.service/\n\n ** Collecting output of: /opt/puppetlabs/puppet/bin/facter --puppet --json --debug >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/system/facter_output.json' 2>&1\n\n ** Collecting output of: /opt/puppetlabs/puppet/bin/gem list --local >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/enterprise/puppet_gems.txt' 2>&1\n\n ** Collecting output of: ping -c 1 puppet.pe-compiler-lb-5b36b6.il4.us-west1.lb.customer-support-scratchpad.internal >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/networking/puppet_ping.txt' 2>&1\n\n ** Copying: /opt/puppetlabs/puppet/cache/state/classes.txt\n\n ** Copying: /opt/puppetlabs/puppet/cache/state/graphs/\n\n ** Copying: /opt/puppetlabs/puppet/cache/state/resources.txt\n\n ** Collecting output of: find '/etc/puppetlabs' \\( -name .snapshot -o -name .snapshots -o -name .backup \\) -prune -o -ls | gzip -f9 >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/enterprise/find/_etc_puppetlabs.txt.gz' 2>&1\n\n ** Collecting output of: find '/var/log/puppetlabs' \\( -name .snapshot -o -name .snapshots -o -name .backup \\) -prune -o -ls | gzip -f9 >> '/var/tmp/puppet_enterprise_support_3_testnode-a1a69d-0_20231103161021/enterprise/find/_var_log_puppetlabs.txt.gz' 2>&1\n\n ** Collecting  [...]

2023-11-06 19:06 UTC, m0dular requested changes
`52c0c9c` is another merge of `main` into your feature branch.  When a feature needs updating after `main` receives new commits, it should always be via `git pull --rebase`.  Does this config setting not work for VS code or something?

```
git config --global pull.rebase true
```

You should be able to fix this branch with the command below again, but please ensure that updating feature branches is done with `pull --rebase` in the future.

```
git pull --rebase origin main -X theirs
```

2023-11-06 19:06 UTC, m0dular commented on README.md
> +| st0305_support_script_and_upload | MFT and P1 are the preferred methods for upload |
This should link to the [kb article](https://perforce1--uat.sandbox.my.site.com/Community2/s/article/360009970114) for MFT uploads.

2023-11-07 11:39 UTC, MartyEwings commented
can you rebase using the command @m0dular mentioned

2023-11-07 13:24 UTC, MartyEwings requested changes

2023-11-07 13:24 UTC, MartyEwings commented on README.md
> +| st0305_support_script_and_upload | MFT and P1 are the preferred methods for upload, see [MFT Documentation](https://portal.perforce.com/s/article/360009970114) for steps|
can this be changed to something like see the following for upload methods?  SFTP and MFT are the preferred options. and sftp has the same function built into to pe that this script used to perform

2023-11-07 13:24 UTC, MartyEwings commented on tasks/st0305_support_script_and_upload.rb
> +deprecation_msg = "This task is deprecated and has been replaced by the certificate clean api, which provides the same functionality.
this message is entirely incorrect its not for this task

2023-11-07 14:13 UTC, Aaronoftheages commented
Seeing validation errors, running `pdk validate -a`

2023-11-07 15:00 UTC, MartyEwings requested changes

2023-11-07 15:00 UTC, MartyEwings commented on tasks/st0305_support_script_and_upload.rb
> +deprecation_msg = "This task is deprecated with support script uploading to be handled manually, and will be removed in a future release.
Its not manually its just done on the command line rather than the UI, so "according to documentation" is a better choice of phrase

2023-11-07 18:09 UTC, m0dular approved these changes

2023-11-07 18:11 UTC, m0dular commented
I think @MartyEwings also needs to approve to satisfy the branch protection rules?

2023-11-07 18:13 UTC, MartyEwings approved these changes

2023-11-08 08:53 UTC, merged